### ISSUE TITLE
Problema ao buildar no swift 5.3.2

### ISSUE THREAD

**Issue by Abel13** [combateafraude/iOS#1]
Oi, estou com um problema ao buildar o app usando o PassiveFaceLiveness.framework no swift 5.3.2
o xcode é o 12.3

<img width="734" alt="Screen Shot 2021-01-21 at 15 26 39" src="https://user-images.githubusercontent.com/1572407/105395042-13161580-5bfd-11eb-9272-7d7e14f7b7b3.png">

<img width="861" alt="Screen Shot 2021-01-21 at 15 24 11" src="https://user-images.githubusercontent.com/1572407/105394800-ca5e5c80-5bfc-11eb-857f-5305b3ed5992.png">

alguém já passou por esse problema?

**Comment by ohenrique** [comment]
Estou enfrentando o mesmo problema, pelo o que entendi só funciona com o XCode 12.5 +.

Alguém sabe de algum workaround para funcionar nos outros XCodes?

**Comment by dbseitenfus** [comment]
Olá, pessoal. As versões PassiveFaceLiveness (3.3.9) e DocumentDetector (4.4.6) devem corrigir esse problema.
