### ISSUE TITLE
Problema ao fazer build no Xcode 13 - Swift 5.5

### ISSUE THREAD

**Issue by leonardo-ferreira07** [combateafraude/iOS#2]
<img width="1076" alt="Screen Shot 2021-09-21 at 10 17 11" src="https://user-images.githubusercontent.com/15631165/134177444-da6bee66-ddd6-41f8-ad75-fe1c4231b35d.png">

**Comment by dbseitenfus** [comment]
Olá, @leonardo-ferreira07. Obrigado pelo report.
As versões DocumentDetector (4.7.6), PassiveFaceLiveness (3.6.7) e FaceAuthenticator (2.4.1) estão com suporte ao Xcode 13 e Swift 5.5.
