### ISSUE TITLE
Problema ao fazer build no xcode 13.2

### ISSUE THREAD

**Issue by ednofedulo** [combateafraude/iOS#3]
![erro](https://gcdn.pbrd.co/images/amc32OZLXUzR.png?o=1)

Module compiled with Swift 5.5.1 cannot be imported by the Swift 5.5.2 compiler

Xcode 13.2 (13C90)

Utilizando o framework PassiveFaceLivenessNosentry

**Comment by dbseitenfus** [comment]
Olá, @ednofedulo!
Novas versões com compatibilidade ao Swift 5.5.2 estão disponíveis. Você pode conferir na nossa documentação https://docs.combateafraude.com/docs/mobile/ios/release-notes/#23-de-dezembro-de-2021

**Comment by ednofedulo** [comment]
Oi, @dbseitenfus 
O pod que eu utilizo é o PassiveFaceLivenessNosentry, este não foi atualizado
