### ISSUE TITLE
Suporte a arm64 arch

### ISSUE THREAD

**Issue by brn-42** [combateafraude/iOS#5]
Pessoal gostaria de saber se existe alguma previsão para o suporte a `arm64` para simuladores.

reparei que o spec do projeto estava setando excluded archs.

```ruby
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

Obrigado

**Comment by dbseitenfus** [comment]
Olá, @brn-42. Experimente as versões [DocumentDetector-7.8.0](https://github.com/combateafraude/iOS/releases/tag/DocumentDetector-7.8.0), [PassiveFaceLiveness-5.24.0](https://github.com/combateafraude/iOS/releases/tag/PassiveFaceLiveness-5.24.0) e [FaceAuthenticator-5.10.0](https://github.com/combateafraude/iOS/releases/tag/FaceAuthenticator-5.10.0).

**Comment by brn-42** [comment]
@dbseitenfus Deu certo, super obrigado!
